#!/usr/bin/env bash
# IFS=: istifadə edərək /etc/passwd faylını parçalayıb while ilə oxuyuruq
while IFS=: read -r USER PASSWORD UID GID USERINFO HOME SHELL
do
    echo "The user $USER is part of the $GID gang, lives in $HOME and rides $SHELL. $UID's place is protected by the passcode $PASSWORD, more info about the user here: $USERINFO"
done < /etc/passwd
