#!/usr/bin/env bash
# Script that handles signals and manages PID file

echo $$ > /var/run/myscript.pid

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"; rm -f /var/run/myscript.pid; exit' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT
trap 'rm -f /var/run/myscript.pid; exit' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
