#!/usr/bin/env bash
# script that manage PID file and handle signals

# Create PID file
echo $$ > /var/run/myscript.pid

# Handle SIGTERM
trap 'echo "I hate the kill command"' SIGTERM

# Handle SIGINT (Ctrl + C)
trap 'echo "Y U no love me?!?"' SIGINT

# Handle SIGQUIT + SIGTERM (delete file and exit)
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
