#!/usr/bin/env bash
# Stop the 4-to_infinity_and_beyond process

# Find the PID(s) of the running process
pid=$(pgrep -f 4-to_infinity_and_beyond)

# Kill the process
if [ -n "$pid" ]; then
    kill "$pid"
fi
